blank_issues_enabled: false
contact_links:
  - name: Voir le CyberPanorama en ligne
    url: https://rustaddict.github.io/test-3/
    about: Consulter le panorama avant de proposer un ajout ou une modification.
